config/routes.rb
Rails.application.routes.draw do
  root 'homepages#index'

  get 'users' => 'homepages#users'
  get 'settings' => 'homepages#settings'
  post 'update_settings' => 'homepages#update_settings'
  devise_for :users
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/setting_option.rb
class SettingOption < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable, :recoverable,
	 :rememberable, :trackable, :validatable, authentication_keys: [:login]

	attr_writer :login
	
	def login
		@login || self.username || self.email
	end

	def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  	def configure_permitted_parameters
  		added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]

  		devise_parameter_sanitizer.permit :sign_in, keys: [added_attrs]
	    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
	    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
  	@column_to_show = SettingOption.where("is_showed = true").order(:id)
  	values = [{:option => "Name Of Client", :option_value => :name_of_client},
		{:option => "Trade Name", :option_value => :trade_name},
		{:option => "Kind Of Receipt", :option_value => :kind_of_receipt},
		{:option => "TIN", :option_value => :tin},
		{:option => "RDO/BIR", :option_value => :rdo_bir},
		{:option => "Size", :option_value => :size},
		{:option => "QTY", :option_value => :qty},
		{:option => "Ply", :option_value => :ply},
		{:option => "Unit Price", :option_value => :unit_price},
		{:option => "Amount", :option_value => :amount},
		{:option => "Contact Person", :option_value => :contact_person},
		{:option => "Contact Number", :option_value => :contact_number},
		{:option => "JO#", :option_value => :jo_num},
		{:option => "Remarks", :option_value => :remarks},
		{:option => "Date Applied", :option_value => :date_applied},
		{:option => "Date Received", :option_value => :date_received},
		{:option => "Date Delivered", :option_value => :date_delivered},
		{:option => "Date Released", :option_value => :date_released},
		{:option => "Status", :option_value => :status}]
	@to_search = []
	@column_to_show.each do |column|
		@to_search.push values.detect{ |value| value[:option] == column.option_name }[:option_value]
	end
	@customers = Customer.select(@to_search.join(', '))

  end
  
  def users
  	
  end

  def update_settings
  	SettingOption.all.update_all(is_showed: false)
  	if params[:settings].present?
  		SettingOption.where("option_name in (?)", params[:settings][:options]).update_all(is_showed: true)
	end
    redirect_to settings_path
  end

  def settings
  	@settings = SettingOption.order(:id)
  	@temp_count = 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/index.html.erb
<% content_for :set_active_customers, "active" %>
<% content_for :assets_css do %>
	<%= stylesheet_link_tag    'ie10-viewport-bug-workaround', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'navbar-fixed-top', media: 'all', 'data-turbolinks-track' => true %>
<% end %>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-5 col-lg-6" style="margin-bottom: 5px;">
		<input type="text" style="border-radius: 5px; border: solid 1.5px #dedede; padding: 6px;" class="col-xs-12 col-sm-12 col-md-12 col-lg-12" placeholder="Search Customer/Trade Name">
	</div>
	<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4" style="margin-bottom: 5px;">
		<!-- <input class="" placeholder="Search Customer/Trade Name"> -->
		<select type="text" style="border-radius: 5px; border: solid 1.5px #dedede; padding: 6px;" class="form-control col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<option selected disabled>Sort table by: id (default)</option>
			<% @column_to_show.each do |column| %>
				<option><%= column.option_name %></option>
			<% end %>
		</select>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-3 col-lg-2" style="margin-bottom: 5px;">
		<button class="btn btn-success btn-block">Add Customer</button>
	</div>
</div>

<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<div class="table-responsive">          
			<table class="table table-striped table-bordered">
				<thead>
					<tr class="success">
						<% @column_to_show.each do |column| %>
							<th><%= column.option_name %></th>
						<% end %>
					</tr>
				</thead>
				<tbody>
					<% @customers.each do |customer| %>
						<tr>
							<% @to_search.each do |to_display| %>
								<th><%= customer[to_display] %></th>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/homepages/settings.html.erb
<% content_for :set_active_settings, "active" %>
<% content_for :assets_css do %>
	<%= stylesheet_link_tag    'ie10-viewport-bug-workaround', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'navbar-fixed-top', media: 'all', 'data-turbolinks-track' => true %>
<% end %>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xm-12">
		<div class="container-fluid">
			<div class="jumbotron">
				<h3 align="center" style="margin-top: -20px;">Show Columns</h3><br>
				<div class="container-fluid">
					<%= form_for(SettingOption.new, as: :settings, url: update_settings_path) do |f| %>
						<div class="row">
							<div class="col-md-12">
								<% @settings.each do |setting| %>
									<%= "<div class='col-lg-3 col-md-3 col-sm-12 col-xm-12' >".html_safe if(@temp_count == 1 || @temp_count == 6 || @temp_count == 11 || @temp_count == 16) %>
									<input type="checkbox" name="settings[options][]" value="<%= setting.option_name %>" <%= setting.is_showed ? "checked" : nil %> id="<%= setting.option_name %>">&nbsp;
									<label for="<%= setting.option_name %>" style="font-size: 16px;"><%= setting.option_name %></label><br>
									<%= "</div>".html_safe if(@temp_count == 5 || @temp_count == 10 || @temp_count == 15 || @temp_count == 19) %>
									<% @temp_count += 1 %>
								<% end %>
							</div>
							<div class="col-xm-12 col-sm-12 col-md-12 col-lg-12" style="margin-top: 40px;">
								<center> <%= f.submit "Save Changes", class: "btn btn-danger" %> </center>
							</div>
						</div>
					<% end %>
				</div>
				
			</div>
		</div>
	</div>
</div>

app/views/homepages/users.html.erb
<% content_for :set_active_users, "active" %>
<% content_for :assets_css do %>
	<%= stylesheet_link_tag    'ie10-viewport-bug-workaround', media: 'all', 'data-turbolinks-track' => true %>
	<%= stylesheet_link_tag    'navbar-fixed-top', media: 'all', 'data-turbolinks-track' => true %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Joan's System</title>
		<%= csrf_meta_tags %>
		<meta charset="utf-8">
		<meta content="IE=edge" http-equiv="X-UA-Compatible">
		<meta content="width=device-width,initial-scale=1" name="viewport">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
		<% if !current_user.nil? %>
			<%= yield(:assets_css) %>
		<% end %>
	</head>
     
	<body style="background-color:<%= current_user.nil? ? "#7f7f7f" : "white" %>;" >
		<% if !current_user.nil? %>
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- <a class="navbar-brand" href="#">JPP</a> -->
						<%= link_to "JPP", root_path, class: "navbar-brand", method: :get %>
					</div>
					<div id="navbar" class="navbar-collapse collapse">
						<ul class="nav navbar-nav">
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="<%= yield(:set_active_customers) %>"><%= link_to "Customers", root_path, method: :get %></li>
							<!-- <li class="<%= yield(:set_active_users) %>"><%= link_to "Users", users_path, method: :get %></li> -->
							<li class="<%= yield(:set_active_settings) %>"><%= link_to "Settings", settings_path, method: :get %></li>
							<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
						</ul>
					</div>
				</div>
			</nav>

			<div class="container-fluid">
				<%= yield %>
			</div> 		
		<% else %>
			<style type="text/css">
				html, body, .container {
					height: 100%;
				}
			</style>
			<div class="container" style="margin-top: 0px; width: 100%;">
				<div class="loginmodal-container">
					<h1>Joan's Printing Press</h1><br>
					<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
						<%= f.text_field :login, placeholder: "Username", autofocus: true %>
						<%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
						<%= f.submit "Log in", class: "login loginmodal-submit" %>
					<% end %>

					<% flash.each do |name, msg| %>
						<center style="margin-top: 5px; color: <%= name == "alert" ? :red : :green %>;">
							<%= msg %>
						</center>
					<% end %>
					
				</div>
			</div>
		<% end %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	</body>
</html>